homepage: "https://www.busybox.net/"
language: c
primary_contact: "vda.linux@googlemail.com"
main_repo: 'git://busybox.net/busybox.git'
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
env:
  - ASAN_OPTIONS=detect_leaks=0